MC = "void" "main" "(" ")" "{"
 [ VarDecl ]
 StatSeq
 "}" .
VarDecl = "int" ident { "," ident } ";" .
StatSeq = Stat { Stat } .
Stat = [ ident "=" Expr
 | "scanf" "(" ident ")"
 | "printf" "(" Expr ")"
 ] ";" .
Expr = Term { ( "+" | "-" ) Term } .
Term = Fact { ( "*" | "/" ) Fact } .
Fact = ident | number | "(" Expr ")" .
