MCP1 =  VarDecl | eps
MC = "void" "main" "(" ")" "{" MCP1 StatSeq "}" 

VarDeclP1P1 =  "," ident 
VarDeclP1 = VarDeclP1 VarDeclP1P1 | eps
VarDecl = "int" ident VarDeclP1 ";" 

StatSeqP1P1 =  Stat 
StatSeqP1 = StatSeqP1 StatSeqP1P1 | eps
StatSeq = Stat StatSeqP1 

StatP1 =  ident "=" Expr | "scanf" "(" ident ")" | "printf" "(" Expr ")" | eps
Stat = StatP1 ";" 

ExprP1P1P1 =  "+" | "-" 
ExprP1P1 =  ExprP1P1P1 Term 
ExprP1 = ExprP1 ExprP1P1 | eps
Expr = Term ExprP1 

TermP1P1P1 =  "*" | "/" 
TermP1P1 =  TermP1P1P1 Fact 
TermP1 = TermP1 TermP1P1 | eps
Term = Fact TermP1 

Fact = ident | number | "(" Expr ")" 