GP1P1P1 =  b | c 
GP1P1 =  a | GP1P1P1 | d 
GP1 =  GP1P1 | e 
GP2 =  f | g 
G = GP1 | GP2 

HP1 =  c | d 
H = a | b HP1 

IP1P1 =  A | B | c 
IP1 = IP1 IP1P1 | eps
I = a | b IP1 

AP1 =  "+" | "-" | eps
A = AP1 

BP1 =  "*" | "/" | eps
B = BP1 t 

XP1P1 =  a | b | c 
XP1 = XP1 XP1P1 | eps
XP2P1 =  d | e 
XP2 = XP2 XP2P1 | eps
X = XP1 | XP2 

YP1P1P1P1 =  b | c 
YP1P1P1 = YP1P1P1 YP1P1P1P1 | eps
YP1P1 =  a | YP1P1P1 
YP1 = YP1 YP1P1 | eps
Y = YP1 