A = ( a | b ) .
B = ( a | b ) ( a | b ) .
C = ( a | b ) ( a | b ) ( a | b ) .
D = ( a | b | c | d ) .
E = ( a | b | c | d ) ( a | b | c | d ) .
F = ( a | b | c | d ) ( a | b | c | d ) ( a | b | c | d ) .
G = ( ( a | ( b | c ) | d ) | e ) | ( f | g ) .